# This file was generated by GoReleaser. DO NOT EDIT.
class PaymailInspector < Formula
  desc "CLI app for interacting with paymail service providers
"
  homepage "https://github.com/mrz1836/paymail-inspector"
  version "0.3.2"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/mrz1836/paymail-inspector/releases/download/v0.3.2/paymail-inspector_macOS_64-bit.tar.gz"
    sha256 "87653420f1e5809bab0164fc2dd0c572636196cd85577ef488b2b88731f495d4"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/mrz1836/paymail-inspector/releases/download/v0.3.2/paymail-inspector_Linux_64-bit.tar.gz"
      sha256 "51284133328de03895afacd8f8411ff6f538d4790b1c6725fa6ff1b4d4c70fdc"
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/mrz1836/paymail-inspector/releases/download/v0.3.2/paymail-inspector_Linux_arm64.tar.gz"
        sha256 "99428b6b9c468220de4920e44d032fb36f852f2f9ddc426bfe4302416834f156"
      else
      end
    end
  end

  def install
    bin.install "paymail"
  end

  def caveats; <<~EOS
    See the Github repo for more information
  EOS
  end

  test do
    system "#{bin}/paymail", "--version"
    system "#{bin}/paymail", "-h"
  end
end
